version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      #- NODE_ENV=production
      # Please specify your configuration in public/config.json
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    #command: "npm start"
    command: "npm start"
    networks:
      - "proxy_default"
networks:
  proxy_default:
    external:
      name: proxy_default