version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      #- NODE_ENV=production
      - VIDEO_IP=
      - VIDEO_PORT=
      - WEBRTC_IP=
      - WEBRTC_PORT=
      - UI_PORT=443 # must be equal to expose or ports
      - UI_SSL=false # if true, ssl certificate and key must be provided in ssl folder named key.pem and cert.pem
      # more configuration can be made in config.json
    volumes:
      - ./:/home/node/app
    expose:
      - "443"
    #command: "npm start"
    command: bash -c "npm install && npm start"
