version: "2"
services:
  node:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      #- NODE_ENV=production
      VIDEO_IP=
      VIDEO_PORT=
      WEBRTC_IP=
      WEBRTC_PORT=
      # more configuration can be made in config.json
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    #command: "npm start"
    command: "npm start"
